/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GoldenCage.Presentation;

import java.awt.CardLayout;

/**
 *
 * @author lenovo_B
 */
public class ListePrestataire extends javax.swing.JPanel {

    /**
     * Creates new form ListePrestataire
     */
    
    
    public ListePrestataire() {
        initComponents();
    }

    public void GoListeProduit(){
        CardLayout card = (CardLayout) PanelPrestataire.getLayout();
        card.show(PanelPrestataire, "CardPrestataire");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrestataire = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblPrix2 = new javax.swing.JLabel();
        lblDesc2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        PanelPrestataire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPrestataireMouseClicked(evt);
            }
        });
        PanelPrestataire.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelPrestataireMouseMoved(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel11.setText("Prestataire");

        jLabel12.setText("Photo");

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setText("Présentation");

        jLabel14.setText("Adresse :");

        jLabel15.setText("Tel :");

        lblPrix2.setText("........");

        lblDesc2.setText("..........");

        jLabel1.setText("Fax :");

        jLabel2.setText("Adresse mail :");

        jLabel3.setText("..........");

        jLabel4.setText(".........");

        javax.swing.GroupLayout PanelPrestataireLayout = new javax.swing.GroupLayout(PanelPrestataire);
        PanelPrestataire.setLayout(PanelPrestataireLayout);
        PanelPrestataireLayout.setHorizontalGroup(
            PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrestataireLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrestataireLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(197, 197, 197))
                    .addGroup(PanelPrestataireLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPrix2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(138, 138, 138))))
            .addGroup(PanelPrestataireLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelPrestataireLayout.setVerticalGroup(
            PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrestataireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(9, 9, 9)
                .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblPrix2))
                .addGap(9, 9, 9)
                .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblDesc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPrestataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        add(PanelPrestataire, "CardPrestataire");
    }// </editor-fold>//GEN-END:initComponents

    private void PanelPrestataireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPrestataireMouseClicked
        // TODO add your handling code here:
        GoListeProduit();
    }//GEN-LAST:event_PanelPrestataireMouseClicked

    private void PanelPrestataireMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPrestataireMouseMoved
        // TODO add your handling code here:
        PanelPrestataire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_PanelPrestataireMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrestataire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDesc2;
    private javax.swing.JLabel lblPrix2;
    // End of variables declaration//GEN-END:variables
}
