/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GoldenCage.Presentation.Clientpack;

import GoldenCage.Presentation.Connexion;
import com.lowagie.text.Font;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.ConnectException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lenovo_B
 */
public class Client extends javax.swing.JFrame {
  
    
 Connexion cd =null;
    public Client(Connexion c) {
        cd=c;
        initComponents();
        panel2_Mariée.setVisible(false);
        panel2_Marié.setVisible(false);
        panel2_Réception.setVisible(false);
        panel2_Animation.setVisible(false);
        panel2_Gastronomie.setVisible(false);
        panel2_Photographe.setVisible(false);
        panel2_Lune.setVisible(false);
        lblBienvenue.setText("Bienvenue "+c.getLoginInput().getText());
    }

    private Client() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
   
     public void GoListeProduit(){
        CardLayout card = (CardLayout) panel1.getLayout();
        card.show(panel1, "CardProduit");
    }
     
       public void GoListePrestataire(){
        CardLayout card = (CardLayout) panel1.getLayout();
        card.show(panel1, "CardPrestataire");
    }
       
        public void GoInfo(){
        panel1.removeAll();
        CardLayout card = (CardLayout) panel1.getLayout();
        card.show(panel1, "CardInfo");
    }
       
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        PanelPrestataire = new GoldenCage.Presentation.Clientpack.ListePrestataire(cd.getLoginInput().getText());
        panel2 = new javax.swing.JPanel();
        lblMariée = new javax.swing.JLabel();
        lblMarié = new javax.swing.JLabel();
        lblRéception = new javax.swing.JLabel();
        lblAnimation = new javax.swing.JLabel();
        lblGastronomie = new javax.swing.JLabel();
        lblPhotographe = new javax.swing.JLabel();
        lblLune = new javax.swing.JLabel();
        panel2_Marié = new javax.swing.JPanel();
        lblCostume = new javax.swing.JLabel();
        lblBeauté = new javax.swing.JLabel();
        lblAccessoire = new javax.swing.JLabel();
        panel2_Réception = new javax.swing.JPanel();
        lblSalleDeFête = new javax.swing.JLabel();
        lblFleuriste = new javax.swing.JLabel();
        lblDécorateur = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblOraganisateurs = new javax.swing.JLabel();
        lblVéhicule = new javax.swing.JLabel();
        lblCortègeEnfants = new javax.swing.JLabel();
        panel2_Gastronomie = new javax.swing.JPanel();
        lblDragéesChocolats = new javax.swing.JLabel();
        lblPâtisserie = new javax.swing.JLabel();
        lblJus = new javax.swing.JLabel();
        panel2_Animation = new javax.swing.JPanel();
        lblDJ = new javax.swing.JLabel();
        lblHadhra = new javax.swing.JLabel();
        lblChanteurs = new javax.swing.JLabel();
        lblDenseuse = new javax.swing.JLabel();
        lblTroupeMusicale = new javax.swing.JLabel();
        panel2_Mariée = new javax.swing.JPanel();
        lblRobeMariée = new javax.swing.JLabel();
        lblRobeSoirée = new javax.swing.JLabel();
        lblCoiffure = new javax.swing.JLabel();
        lblHauteCouture = new javax.swing.JLabel();
        lblLangerie = new javax.swing.JLabel();
        panel2_Lune = new javax.swing.JPanel();
        lblAgence = new javax.swing.JLabel();
        panel2_Photographe = new javax.swing.JPanel();
        lblPhotogr = new javax.swing.JLabel();
        lblBienvenue = new javax.swing.JLabel();
        lblDeconnexion = new javax.swing.JLabel();
        lblGerer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 2));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel1MouseMoved(evt);
            }
        });
        panel1.setLayout(new java.awt.CardLayout());
        panel1.add(PanelPrestataire, "CardPrestataire");

        panel2.setBackground(new java.awt.Color(255, 0, 102));
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel2MouseExited(evt);
            }
        });

        lblMariée.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblMariée.setText("Mariée");
        lblMariée.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMariéeMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMariéeMouseClicked(evt);
            }
        });
        lblMariée.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMariéeMouseMoved(evt);
            }
        });

        lblMarié.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblMarié.setText("Marié");
        lblMarié.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMariéMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMariéMouseClicked(evt);
            }
        });
        lblMarié.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMariéMouseMoved(evt);
            }
        });

        lblRéception.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblRéception.setText("Réception");
        lblRéception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRéceptionMouseClicked(evt);
            }
        });
        lblRéception.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRéceptionMouseMoved(evt);
            }
        });

        lblAnimation.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblAnimation.setText("Animation");
        lblAnimation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnimationMouseClicked(evt);
            }
        });
        lblAnimation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAnimationMouseMoved(evt);
            }
        });

        lblGastronomie.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblGastronomie.setText("Gastronomie");
        lblGastronomie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGastronomieMouseClicked(evt);
            }
        });
        lblGastronomie.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblGastronomieMouseMoved(evt);
            }
        });

        lblPhotographe.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblPhotographe.setText("Photographe");
        lblPhotographe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotographeMouseClicked(evt);
            }
        });
        lblPhotographe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPhotographeMouseMoved(evt);
            }
        });

        lblLune.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        lblLune.setText("Lune de Miel");
        lblLune.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLuneMouseMoved(evt);
            }
        });

        panel2_Marié.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Marié.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_MariéMouseMoved(evt);
            }
        });

        lblCostume.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblCostume.setText("Costume de Mariage");

        lblBeauté.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblBeauté.setText("Soins Beauté");

        lblAccessoire.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblAccessoire.setText("Accessoire Marié");

        javax.swing.GroupLayout panel2_MariéLayout = new javax.swing.GroupLayout(panel2_Marié);
        panel2_Marié.setLayout(panel2_MariéLayout);
        panel2_MariéLayout.setHorizontalGroup(
            panel2_MariéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_MariéLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2_MariéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccessoire)
                    .addComponent(lblBeauté)
                    .addComponent(lblCostume))
                .addContainerGap(1115, Short.MAX_VALUE))
        );
        panel2_MariéLayout.setVerticalGroup(
            panel2_MariéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_MariéLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCostume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBeauté, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAccessoire, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel2_Réception.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Réception.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_RéceptionMouseMoved(evt);
            }
        });

        lblSalleDeFête.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblSalleDeFête.setText("Salle de Fête");

        lblFleuriste.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblFleuriste.setText("Fleuriste");

        lblDécorateur.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblDécorateur.setText("Décorateur");

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel14.setText("Invitations");

        lblOraganisateurs.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblOraganisateurs.setText("Oraganisateurs");

        lblVéhicule.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblVéhicule.setText("Véhicule de Prestige");

        lblCortègeEnfants.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblCortègeEnfants.setText("Cortège enfants");

        javax.swing.GroupLayout panel2_RéceptionLayout = new javax.swing.GroupLayout(panel2_Réception);
        panel2_Réception.setLayout(panel2_RéceptionLayout);
        panel2_RéceptionLayout.setHorizontalGroup(
            panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_RéceptionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFleuriste)
                    .addComponent(lblSalleDeFête)
                    .addComponent(lblDécorateur))
                .addGap(72, 72, 72)
                .addGroup(panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVéhicule)
                    .addGroup(panel2_RéceptionLayout.createSequentialGroup()
                        .addComponent(lblOraganisateurs)
                        .addGap(107, 107, 107)
                        .addComponent(lblCortègeEnfants))
                    .addComponent(jLabel14))
                .addContainerGap(751, Short.MAX_VALUE))
        );
        panel2_RéceptionLayout.setVerticalGroup(
            panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_RéceptionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalleDeFête)
                    .addComponent(lblOraganisateurs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCortègeEnfants))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFleuriste, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2_RéceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDécorateur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVéhicule, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel2_Gastronomie.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Gastronomie.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_GastronomieMouseMoved(evt);
            }
        });

        lblDragéesChocolats.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblDragéesChocolats.setText("Dragées et Chocolats");

        lblPâtisserie.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblPâtisserie.setText("Pâtisserie");

        lblJus.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblJus.setText("Jus");

        javax.swing.GroupLayout panel2_GastronomieLayout = new javax.swing.GroupLayout(panel2_Gastronomie);
        panel2_Gastronomie.setLayout(panel2_GastronomieLayout);
        panel2_GastronomieLayout.setHorizontalGroup(
            panel2_GastronomieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_GastronomieLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel2_GastronomieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPâtisserie)
                    .addComponent(lblDragéesChocolats)
                    .addComponent(lblJus))
                .addContainerGap(1106, Short.MAX_VALUE))
        );
        panel2_GastronomieLayout.setVerticalGroup(
            panel2_GastronomieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_GastronomieLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDragéesChocolats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPâtisserie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel2_Animation.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Animation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_AnimationMouseMoved(evt);
            }
        });

        lblDJ.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblDJ.setText("DJ");

        lblHadhra.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblHadhra.setText("Hadhra");

        lblChanteurs.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblChanteurs.setText("Chanteurs");

        lblDenseuse.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblDenseuse.setText("Denseuse Orientale");

        lblTroupeMusicale.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblTroupeMusicale.setText("Troupe Musicale");

        javax.swing.GroupLayout panel2_AnimationLayout = new javax.swing.GroupLayout(panel2_Animation);
        panel2_Animation.setLayout(panel2_AnimationLayout);
        panel2_AnimationLayout.setHorizontalGroup(
            panel2_AnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_AnimationLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel2_AnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHadhra)
                    .addComponent(lblChanteurs)
                    .addComponent(lblTroupeMusicale))
                .addGap(72, 72, 72)
                .addGroup(panel2_AnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDenseuse)
                    .addComponent(lblDJ))
                .addContainerGap(915, Short.MAX_VALUE))
        );
        panel2_AnimationLayout.setVerticalGroup(
            panel2_AnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_AnimationLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel2_AnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenseuse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTroupeMusicale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2_AnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHadhra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChanteurs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel2_Mariée.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Mariée.setMaximumSize(new java.awt.Dimension(400, 300));
        panel2_Mariée.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_MariéeMouseMoved(evt);
            }
        });

        lblRobeMariée.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblRobeMariée.setText("Robe de Mariée");
        lblRobeMariée.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRobeMariéeMouseClicked(evt);
            }
        });
        lblRobeMariée.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRobeMariéeMouseMoved(evt);
            }
        });

        lblRobeSoirée.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblRobeSoirée.setText("Robe de Soirée");
        lblRobeSoirée.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRobeSoiréeMouseClicked(evt);
            }
        });
        lblRobeSoirée.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRobeSoiréeMouseMoved(evt);
            }
        });

        lblCoiffure.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblCoiffure.setText("Coiffure et Beauté");
        lblCoiffure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCoiffureMouseClicked(evt);
            }
        });
        lblCoiffure.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCoiffureMouseMoved(evt);
            }
        });

        lblHauteCouture.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblHauteCouture.setText("Haute Couture");
        lblHauteCouture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHauteCoutureMouseClicked(evt);
            }
        });
        lblHauteCouture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblHauteCoutureMouseMoved(evt);
            }
        });

        lblLangerie.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblLangerie.setText("Langerie");
        lblLangerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLangerieMouseClicked(evt);
            }
        });
        lblLangerie.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLangerieMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout panel2_MariéeLayout = new javax.swing.GroupLayout(panel2_Mariée);
        panel2_Mariée.setLayout(panel2_MariéeLayout);
        panel2_MariéeLayout.setHorizontalGroup(
            panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_MariéeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoiffure)
                    .addGroup(panel2_MariéeLayout.createSequentialGroup()
                        .addGroup(panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRobeSoirée)
                            .addComponent(lblRobeMariée))
                        .addGap(72, 72, 72)
                        .addGroup(panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLangerie)
                            .addComponent(lblHauteCouture))))
                .addContainerGap(952, Short.MAX_VALUE))
        );
        panel2_MariéeLayout.setVerticalGroup(
            panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_MariéeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRobeMariée)
                    .addComponent(lblLangerie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2_MariéeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRobeSoirée, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHauteCouture, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCoiffure, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panel2_Lune.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Lune.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_LuneMouseMoved(evt);
            }
        });

        lblAgence.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblAgence.setText("Agence de Voyage");

        javax.swing.GroupLayout panel2_LuneLayout = new javax.swing.GroupLayout(panel2_Lune);
        panel2_Lune.setLayout(panel2_LuneLayout);
        panel2_LuneLayout.setHorizontalGroup(
            panel2_LuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_LuneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAgence)
                .addContainerGap(1121, Short.MAX_VALUE))
        );
        panel2_LuneLayout.setVerticalGroup(
            panel2_LuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_LuneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblAgence)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        panel2_Photographe.setBackground(new java.awt.Color(247, 156, 192));
        panel2_Photographe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel2_PhotographeMouseMoved(evt);
            }
        });

        lblPhotogr.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblPhotogr.setText("Photographe");

        javax.swing.GroupLayout panel2_PhotographeLayout = new javax.swing.GroupLayout(panel2_Photographe);
        panel2_Photographe.setLayout(panel2_PhotographeLayout);
        panel2_PhotographeLayout.setHorizontalGroup(
            panel2_PhotographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_PhotographeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblPhotogr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2_PhotographeLayout.setVerticalGroup(
            panel2_PhotographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2_PhotographeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPhotogr)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMariée)
                .addGap(18, 18, 18)
                .addComponent(lblMarié)
                .addGap(18, 18, 18)
                .addComponent(lblRéception)
                .addGap(18, 18, 18)
                .addComponent(lblAnimation)
                .addGap(21, 21, 21)
                .addComponent(lblGastronomie)
                .addGap(18, 18, 18)
                .addComponent(lblPhotographe)
                .addGap(31, 31, 31)
                .addComponent(lblLune)
                .addContainerGap())
            .addComponent(panel2_Photographe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2_Marié, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2_Réception, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2_Gastronomie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2_Animation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2_Lune, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2_Mariée, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMariée)
                    .addComponent(lblMarié)
                    .addComponent(lblRéception)
                    .addComponent(lblAnimation)
                    .addComponent(lblGastronomie)
                    .addComponent(lblPhotographe)
                    .addComponent(lblLune))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2_Photographe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(panel2_Marié, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(panel2_Réception, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(panel2_Gastronomie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(panel2_Animation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(panel2_Lune, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(panel2_Mariée, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        lblBienvenue.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblBienvenue.setText("Bienvenue ");

        lblDeconnexion.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblDeconnexion.setText("Déconnexion");
        lblDeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDeconnexionMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeconnexionMouseClicked(evt);
            }
        });
        lblDeconnexion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDeconnexionMouseMoved(evt);
            }
        });

        lblGerer.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        lblGerer.setText("Gérer Compte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(lblGerer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenue)
                    .addComponent(lblDeconnexion)
                    .addComponent(lblGerer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMariéeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMariéeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMariéeMouseClicked

    private void lblMariéMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMariéMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMariéMouseClicked

    private void lblRéceptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRéceptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRéceptionMouseClicked

    private void lblAnimationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnimationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAnimationMouseClicked

    private void lblGastronomieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGastronomieMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGastronomieMouseClicked

    private void lblPhotographeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotographeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPhotographeMouseClicked

    private void lblMariéeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMariéeMouseMoved
        // TODO add your handling code here:
        lblMariée.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Mariée.setVisible(true);
    }//GEN-LAST:event_lblMariéeMouseMoved

    private void lblMariéMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMariéMouseMoved
        // TODO add your handling code here:
        lblMarié.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Marié.setVisible(true);
    }//GEN-LAST:event_lblMariéMouseMoved

    private void lblRéceptionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRéceptionMouseMoved
        // TODO add your handling code here:
        lblRéception.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         panel2_Réception.setVisible(true);
    }//GEN-LAST:event_lblRéceptionMouseMoved

    private void lblAnimationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnimationMouseMoved
        // TODO add your handling code here:
        lblAnimation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Animation.setVisible(true);
    }//GEN-LAST:event_lblAnimationMouseMoved

    private void lblGastronomieMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGastronomieMouseMoved
        // TODO add your handling code here:
        lblGastronomie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Gastronomie.setVisible(true);
    }//GEN-LAST:event_lblGastronomieMouseMoved

    private void lblPhotographeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotographeMouseMoved
        // TODO add your handling code here:
        lblPhotographe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Photographe.setVisible(true);
    }//GEN-LAST:event_lblPhotographeMouseMoved

    private void lblMariéeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMariéeMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblMariéeMouseExited

    private void lblMariéMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMariéMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMariéMouseExited

    private void panel2_MariéeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_MariéeMouseMoved
        // TODO add your handling code here:
         panel2_Mariée.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         panel2_Mariée.setVisible(true);
    }//GEN-LAST:event_panel2_MariéeMouseMoved

    private void panel2_MariéMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_MariéMouseMoved
        // TODO add your handling code here:
         panel2_Marié.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         panel2_Marié.setVisible(true);
    }//GEN-LAST:event_panel2_MariéMouseMoved

    private void panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseExited
        // TODO add your handling code here:
        panel2_Mariée.setVisible(false);
        panel2_Marié.setVisible(false);
        panel2_Réception.setVisible(false);
        panel2_Animation.setVisible(false);
        panel2_Gastronomie.setVisible(false);
        panel2_Photographe.setVisible(false);
        panel2_Lune.setVisible(false);
    }//GEN-LAST:event_panel2MouseExited

    private void panel2_RéceptionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_RéceptionMouseMoved
        // TODO add your handling code here:
        panel2_Réception.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Réception.setVisible(true);
    }//GEN-LAST:event_panel2_RéceptionMouseMoved

    private void panel2_AnimationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_AnimationMouseMoved
        // TODO add your handling code here:
        panel2_Animation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Animation.setVisible(true);
    }//GEN-LAST:event_panel2_AnimationMouseMoved

    private void panel2_GastronomieMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_GastronomieMouseMoved
        // TODO add your handling code here:
        panel2_Gastronomie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Gastronomie.setVisible(true);
    }//GEN-LAST:event_panel2_GastronomieMouseMoved

    private void panel2_PhotographeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_PhotographeMouseMoved
        // TODO add your handling code here:
        panel2_Photographe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Photographe.setVisible(true);
    }//GEN-LAST:event_panel2_PhotographeMouseMoved

    private void lblLuneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuneMouseMoved
        // TODO add your handling code here:
        lblPhotographe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Lune.setVisible(true);
    }//GEN-LAST:event_lblLuneMouseMoved

    private void panel2_LuneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2_LuneMouseMoved
        // TODO add your handling code here:
        panel2_Lune.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel2_Lune.setVisible(true);
    }//GEN-LAST:event_panel2_LuneMouseMoved

    private void lblRobeMariéeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRobeMariéeMouseClicked
        // TODO add your handling code here:
        GoListePrestataire();
        lblRobeMariée.setForeground(new Color(153, 0, 153));
        lblRobeSoirée.setForeground(Color.BLACK);
        lblCoiffure.setForeground(Color.BLACK);
       lblHauteCouture.setForeground(Color.BLACK);
       lblLangerie.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRobeMariéeMouseClicked

    private void lblRobeMariéeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRobeMariéeMouseMoved
        // TODO add your handling code here:
         lblRobeMariée.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblRobeMariéeMouseMoved

    private void lblRobeSoiréeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRobeSoiréeMouseClicked
        // TODO add your handling code here:
        GoListePrestataire();
        lblRobeSoirée.setForeground(new Color(153, 0, 153));
        lblRobeMariée.setForeground(Color.BLACK);
        lblCoiffure.setForeground(Color.BLACK);
          lblHauteCouture.setForeground(Color.BLACK);
          lblLangerie.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRobeSoiréeMouseClicked

    private void lblCoiffureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCoiffureMouseClicked
        // TODO add your handling code here:
         GoListePrestataire();
         lblRobeMariée.setForeground(Color.BLACK);
         lblRobeSoirée.setForeground(Color.BLACK);
         lblHauteCouture.setForeground(Color.BLACK);
         lblCoiffure.setForeground(new Color(153, 0, 153));
         lblLangerie.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCoiffureMouseClicked

    private void lblCoiffureMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCoiffureMouseMoved
        // TODO add your handling code here:
        lblCoiffure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCoiffureMouseMoved

    private void lblHauteCoutureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHauteCoutureMouseClicked
        // TODO add your handling code here:
         GoListePrestataire();
         lblRobeMariée.setForeground(Color.BLACK);
         lblRobeSoirée.setForeground(Color.BLACK);
         lblCoiffure.setForeground(Color.BLACK);
          lblLangerie.setForeground(Color.BLACK);
         lblHauteCouture.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_lblHauteCoutureMouseClicked

    private void lblLangerieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLangerieMouseClicked
        // TODO add your handling code here:
         GoListePrestataire();
         lblRobeMariée.setForeground(Color.BLACK);
         lblRobeSoirée.setForeground(Color.BLACK);
         lblCoiffure.setForeground(Color.BLACK);
         lblHauteCouture.setForeground(Color.BLACK);
         lblLangerie.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_lblLangerieMouseClicked

    private void lblLangerieMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLangerieMouseMoved
        // TODO add your handling code here:
        lblLangerie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblLangerieMouseMoved

    private void lblHauteCoutureMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHauteCoutureMouseMoved
        // TODO add your handling code here:
         lblHauteCouture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblHauteCoutureMouseMoved

    private void lblRobeSoiréeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRobeSoiréeMouseMoved
        // TODO add your handling code here:
        lblRobeSoirée.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblRobeSoiréeMouseMoved

    private void panel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseMoved
        // TODO add your handling code here:
       /* panel2_Mariée.setVisible(false);
        panel2_Marié.setVisible(false);
        panel2_Réception.setVisible(false);
        panel2_Animation.setVisible(false);
        panel2_Gastronomie.setVisible(false);
        panel2_Photographe.setVisible(false);
        panel2_Lune.setVisible(false);*/
    }//GEN-LAST:event_panel1MouseMoved

    private void lblDeconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeconnexionMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Connexion c = new Connexion();
        c.setVisible(true);
    }//GEN-LAST:event_lblDeconnexionMouseClicked

    private void lblDeconnexionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeconnexionMouseMoved
        // TODO add your handling code here:
        lblDeconnexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDeconnexion.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_lblDeconnexionMouseMoved

    private void lblDeconnexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeconnexionMouseExited
        // TODO add your handling code here:
        lblDeconnexion.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblDeconnexionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GoldenCage.Presentation.Clientpack.ListePrestataire PanelPrestataire;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccessoire;
    private javax.swing.JLabel lblAgence;
    private javax.swing.JLabel lblAnimation;
    private javax.swing.JLabel lblBeauté;
    private javax.swing.JLabel lblBienvenue;
    private javax.swing.JLabel lblChanteurs;
    private javax.swing.JLabel lblCoiffure;
    private javax.swing.JLabel lblCortègeEnfants;
    private javax.swing.JLabel lblCostume;
    private javax.swing.JLabel lblDJ;
    private javax.swing.JLabel lblDeconnexion;
    private javax.swing.JLabel lblDenseuse;
    private javax.swing.JLabel lblDragéesChocolats;
    private javax.swing.JLabel lblDécorateur;
    private javax.swing.JLabel lblFleuriste;
    private javax.swing.JLabel lblGastronomie;
    private javax.swing.JLabel lblGerer;
    private javax.swing.JLabel lblHadhra;
    private javax.swing.JLabel lblHauteCouture;
    private javax.swing.JLabel lblJus;
    private javax.swing.JLabel lblLangerie;
    private javax.swing.JLabel lblLune;
    private javax.swing.JLabel lblMarié;
    private javax.swing.JLabel lblMariée;
    private javax.swing.JLabel lblOraganisateurs;
    private javax.swing.JLabel lblPhotogr;
    private javax.swing.JLabel lblPhotographe;
    private javax.swing.JLabel lblPâtisserie;
    private javax.swing.JLabel lblRobeMariée;
    private javax.swing.JLabel lblRobeSoirée;
    private javax.swing.JLabel lblRéception;
    private javax.swing.JLabel lblSalleDeFête;
    private javax.swing.JLabel lblTroupeMusicale;
    private javax.swing.JLabel lblVéhicule;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel2_Animation;
    private javax.swing.JPanel panel2_Gastronomie;
    private javax.swing.JPanel panel2_Lune;
    private javax.swing.JPanel panel2_Marié;
    private javax.swing.JPanel panel2_Mariée;
    private javax.swing.JPanel panel2_Photographe;
    private javax.swing.JPanel panel2_Réception;
    // End of variables declaration//GEN-END:variables
}
