/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.Presentation.Clientpack;
import GoldenCage.Presentation.Administrateur.AfficherPrestataire;
import GoldenCage.Presentation.Administrateur.ModifierCompte;
import GoldenCage.Presentation.Clientpack.AfficherProduits;
import GoldenCage.dao.*;
import GoldenCage.entities.Prestataire;
import GoldenCage.entities.Produit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Khaled
 */
public class EffectuerAchat extends javax.swing.JFrame {

    /**
     * Creates new form EffectuerAchat
     */
    private int id ;
    public EffectuerAchat(int idClient) {
        id = idClient;
        initComponents();
        lblSale.setVisible(false);
    }

    private EffectuerAchat() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSale = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblConsulterProduit3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblConsulterProduit2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ComboCritere = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 153, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sale.png"))); // NOI18N
        jPanel1.add(lblSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 70, 80));

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 238, 316));

        lblConsulterProduit3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblConsulterProduit3.setText("Photo");
        lblConsulterProduit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsulterProduit3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsulterProduit3MouseExited(evt);
            }
        });
        lblConsulterProduit3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConsulterProduit3MouseMoved(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 204)));

        lblConsulterProduit2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblConsulterProduit2.setText("Critère de recherche");
        lblConsulterProduit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsulterProduit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsulterProduit2MouseExited(evt);
            }
        });
        lblConsulterProduit2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConsulterProduit2MouseMoved(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new AfficherProduits());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ComboCritere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "Trier selon le prix", "Afficher les offres" }));
        ComboCritere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCritereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblConsulterProduit2)
                            .addGap(158, 158, 158)
                            .addComponent(ComboCritere, 0, 373, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsulterProduit2)
                        .addComponent(ComboCritere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ajouterPanier.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblConsulterProduit3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblConsulterProduit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      int idex = jTable1.getSelectedRow();
      String st = (jTable1.getModel().getValueAt(idex, 0).toString());
      ProduitDAO produitDAO=new ProduitDAO();
      ImageIcon icon;
      icon=produitDAO.RechercherProduit(st);
      lblImage.setIcon(icon);
      System.out.print(produitDAO.Soldé(st));
      if (produitDAO.Soldé(st)==true)
          lblSale.setVisible(true);
      else 
          lblSale.setVisible(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void lblConsulterProduit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduit2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsulterProduit2MouseClicked

    private void lblConsulterProduit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsulterProduit2MouseExited

    private void lblConsulterProduit2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduit2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsulterProduit2MouseMoved

    private void ComboCritereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCritereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCritereActionPerformed

    private void lblConsulterProduit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduit3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsulterProduit3MouseClicked

    private void lblConsulterProduit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduit3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsulterProduit3MouseExited

    private void lblConsulterProduit3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduit3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsulterProduit3MouseMoved

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int idex = jTable1.getSelectedRow();
      String st = (jTable1.getModel().getValueAt(idex, 0).toString());
      ProduitDAO produitDAO=new ProduitDAO();
      int idProduit;
      idProduit = produitDAO.RechercherIDProduit(st);
      PanierDAO panier = new PanierDAO();
      panier.InsertIntoPanier(id, idProduit);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EffectuerAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EffectuerAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EffectuerAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EffectuerAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EffectuerAchat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboCritere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblConsulterProduit2;
    private javax.swing.JLabel lblConsulterProduit3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSale;
    // End of variables declaration//GEN-END:variables
}
