/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GoldenCage.Presentation.Clientpack;

import GoldenCage.dao.PrestataireDAO;
import GoldenCage.dao.ProduitDAO;
import GoldenCage.entities.Prestataire;
import GoldenCage.entities.Produit;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lenovo_B
 */
public class imageProduit extends javax.swing.JPanel {

    /**
     * Creates new form imageProduit
     */
    JLabel lbl[][] = new JLabel[5][5];
    public imageProduit() {
         Icon icon = null;
       ProduitDAO p = new ProduitDAO();
       List<Produit>listProduit=new ArrayList<>();
       //listProduit = p.Rechercher();
       System.out.println(listProduit.size());
       for (int i=0;i<listProduit.size();i++){
           icon =listProduit.get(i).getPhotoProduit();
            add(new JLabel(icon));
       }
        /*PrestataireDAO p = new PrestataireDAO();
       List<Prestataire>listPrestataire=new ArrayList<>();
       listPrestataire = p.DisplayAllPrestataire();
       int k=listPrestataire.size();
       System.out.println(listPrestataire.size());
       for (int i=0;i<listPrestataire.size();i++){
           this.add(new JLabel(listPrestataire.get(i).getPhoto()));
       }*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new java.awt.GridLayout(1, 8, 5, 5));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables

    
}
