/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GoldenCage.Presentation.Clientpack;

import GoldenCage.dao.PrestataireDAO;
import GoldenCage.dao.ProduitDAO;
import GoldenCage.entities.Prestataire;
import GoldenCage.entities.Produit;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lenovo_B
 */
public class ImageProd extends javax.swing.JFrame {

    /**
     * Creates new form ImageProd
     */  JLabel lbl[][] = new JLabel[5][5];
    public ImageProd(String nom) {
       ProduitDAO p = new ProduitDAO();
       List<Produit>listProduit=new ArrayList<>();
       listProduit = p.Rechercher(nom);
       int k=0;
       Icon icon = null;
       System.out.println(listProduit.size());
        /*for (int i = 0; i< 5; i++){
        for (int j = 0; j< 5; j++)
        {
          lbl[i][j] = new JLabel();
          lbl[i][j].setIcon(listProduit.get(k).getPhotoProduit());
          add(lbl[i][j]);
        }
        }*/
      
       for (int i=0;i<listProduit.size();i++){
           icon =listProduit.get(i).getPhotoProduit();
            add(new JLabel(icon));
       }
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private ImageProd() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 5));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ImageProd().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
