package GoldenCage.Presentation.Clientpack;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import GoldenCage.Presentation.Clientpack.ImageProd;

import GoldenCage.dao.ClientDAO;
import GoldenCage.dao.PrestataireDAO;
import GoldenCage.entities.Client;
import GoldenCage.entities.Prestataire;
import GoldenCage.entities.Reclamation;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author lenovo_B
 */
public class InfoPrestataire extends javax.swing.JFrame {

    /**
     * Creates new form InfoPrestataire
     */
    JLabel lbl[][] = new JLabel[5][5];

    String nom;
    String nomClient;
    InfoPrestataire() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

   

  

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }
    public InfoPrestataire(String nomCli) {
        nomClient=nomCli;
        System.out.println("yess !!!!!!"+nomCli+"");   
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jPanel2.setVisible(false);
    }
    

    public JLabel getLblNom() {
        return lblNom;
    }

   
    public JLabel getLblAdresse() {
        return lblAdresse;
    }

    public JLabel getLblFax() {
        return lblFax;
    }

    public JLabel getLblMail() {
        return lblMail;
    }

    public JLabel getLblPhoto() {
        return lblPhoto;
    }

    public JLabel getLblTel() {
        return lblTel;
    }

    public JTextArea getLblDescription() {
        return lblDescription;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescription = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblCommentaire = new javax.swing.JTextArea();
        btCommenter = new javax.swing.JButton();
        lblRedigerCommentaire = new javax.swing.JLabel();
        lblConsulterProduit = new javax.swing.JLabel();
        lblAttribuerNote = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        lblNom.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setText("Présentataion");

        jLabel2.setText("Contact :");

        jLabel3.setText("Adresse :");

        jLabel4.setText("Fax :");

        jLabel5.setText("Mail :");

        jLabel6.setText("Description :");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblDescription.setEditable(false);
        lblDescription.setBackground(new java.awt.Color(255, 204, 204));
        lblDescription.setColumns(20);
        lblDescription.setRows(5);
        lblDescription.setMaximumSize(new java.awt.Dimension(60, 20));
        jScrollPane1.setViewportView(lblDescription);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 102, 204)));

        lblCommentaire.setColumns(20);
        lblCommentaire.setRows(5);
        jScrollPane3.setViewportView(lblCommentaire);

        btCommenter.setText("Commenter");
        btCommenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommenterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 806, Short.MAX_VALUE)
                        .addComponent(btCommenter, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btCommenter)
                .addContainerGap())
        );

        lblRedigerCommentaire.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblRedigerCommentaire.setText("Rédiger Commentaire");
        lblRedigerCommentaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRedigerCommentaireMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRedigerCommentaireMouseExited(evt);
            }
        });
        lblRedigerCommentaire.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRedigerCommentaireMouseMoved(evt);
            }
        });

        lblConsulterProduit.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblConsulterProduit.setText("Consulter le produits");
        lblConsulterProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsulterProduitMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsulterProduitMouseClicked(evt);
            }
        });
        lblConsulterProduit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConsulterProduitMouseMoved(evt);
            }
        });

        lblAttribuerNote.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblAttribuerNote.setText("Attribuer une note");
        lblAttribuerNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAttribuerNoteMouseExited(evt);
            }
        });
        lblAttribuerNote.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAttribuerNoteMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(358, 358, 358)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblRedigerCommentaire)
                        .addGap(34, 34, 34)
                        .addComponent(lblConsulterProduit)
                        .addGap(34, 34, 34)
                        .addComponent(lblAttribuerNote))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(lblAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblFax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblMail))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRedigerCommentaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsulterProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAttribuerNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCommenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommenterActionPerformed
        // TODO add your handling code here:
        Client client = new Client();
        ClientDAO c = new ClientDAO();
        client = c.Rechercher(nomClient);
        String date = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
        String time = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
        //Reclamation rec = new Reclamation(null, client.getIdClient(), 1, lblCommentaire.getText(), 25 , date, time);
    }//GEN-LAST:event_btCommenterActionPerformed

    private void lblRedigerCommentaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRedigerCommentaireMouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        
    }//GEN-LAST:event_lblRedigerCommentaireMouseClicked

    private void lblRedigerCommentaireMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRedigerCommentaireMouseMoved
        // TODO add your handling code here:
	lblRedigerCommentaire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRedigerCommentaire.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_lblRedigerCommentaireMouseMoved

    private void lblRedigerCommentaireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRedigerCommentaireMouseExited
        // TODO add your handling code here:
        lblRedigerCommentaire.setText("Rédiger Commentaire");
        lblRedigerCommentaire.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRedigerCommentaireMouseExited

    private void lblConsulterProduitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduitMouseMoved
        // TODO add your handling code here:
	lblConsulterProduit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConsulterProduit.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_lblConsulterProduitMouseMoved

    private void lblConsulterProduitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduitMouseExited
        // TODO add your handling code here:
        lblConsulterProduit.setText("Consulter les produits");
        lblConsulterProduit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblConsulterProduitMouseExited

    private void lblAttribuerNoteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttribuerNoteMouseMoved
        // TODO add your handling code here:
	lblAttribuerNote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAttribuerNote.setForeground(new Color(153, 0, 153));
    }//GEN-LAST:event_lblAttribuerNoteMouseMoved

    private void lblAttribuerNoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttribuerNoteMouseExited
        // TODO add your handling code here:
        lblAttribuerNote.setText("Attribuer une note");
        lblAttribuerNote.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblAttribuerNoteMouseExited

    private void lblConsulterProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulterProduitMouseClicked
        // TODO add your handling code here:
        ImageProd listeProduit = new ImageProd(lblNom.getText());
        listeProduit.setVisible(true);
    }//GEN-LAST:event_lblConsulterProduitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoPrestataire().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCommenter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblAttribuerNote;
    private javax.swing.JTextArea lblCommentaire;
    private javax.swing.JLabel lblConsulterProduit;
    private javax.swing.JTextArea lblDescription;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblRedigerCommentaire;
    private javax.swing.JLabel lblTel;
    // End of variables declaration//GEN-END:variables

}
