/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.Presentation.Administrateur;

import GoldenCage.Presentation.Connexion;

/**
 *
 * @author minoo
 */
public class Choix extends javax.swing.JFrame {

    /**
     * Creates new form Choix
     */
    public Choix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BtRetour = new javax.swing.JButton();
        Jprest = new javax.swing.JButton();
        Jrapport = new javax.swing.JButton();
        Jreclamation = new javax.swing.JButton();
        Jstatistique = new javax.swing.JButton();
        Jclient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choix");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Veuillez selectionner votre choix");

        BtRetour.setText("Retour");
        BtRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRetourActionPerformed(evt);
            }
        });

        Jprest.setText("Gérer les préstataires");
        Jprest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JprestActionPerformed(evt);
            }
        });

        Jrapport.setText("Générer Rapport");
        Jrapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrapportActionPerformed(evt);
            }
        });

        Jreclamation.setText("Consulter les réclamations");
        Jreclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JreclamationActionPerformed(evt);
            }
        });

        Jstatistique.setText("Générer les statistiques");
        Jstatistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JstatistiqueActionPerformed(evt);
            }
        });

        Jclient.setText("Gérer les clients");
        Jclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JclientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtRetour)
                        .addGap(32, 617, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jreclamation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jclient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jstatistique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jrapport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jprest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(254, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(Jprest)
                .addGap(28, 28, 28)
                .addComponent(Jrapport)
                .addGap(36, 36, 36)
                .addComponent(Jreclamation)
                .addGap(32, 32, 32)
                .addComponent(Jstatistique)
                .addGap(29, 29, 29)
                .addComponent(Jclient)
                .addGap(51, 51, 51)
                .addComponent(BtRetour)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(716, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRetourActionPerformed
        // TODO add your handling code here:
        Connexion cn=new Connexion();
        this.setVisible(false);
        cn.setVisible(true);
        
    }//GEN-LAST:event_BtRetourActionPerformed

    private void JprestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JprestActionPerformed
        // TODO add your handling code here:
        GererCompte gc=new GererCompte();
            this.setVisible(false);
            gc.setVisible(true);
    }//GEN-LAST:event_JprestActionPerformed

    private void JrapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrapportActionPerformed
        GenererRapport gr=new GenererRapport();
            this.setVisible(false);
            gr.setVisible(true);
    }//GEN-LAST:event_JrapportActionPerformed

    private void JreclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JreclamationActionPerformed
        // TODO add your handling code here:
         Reclamation rec=new Reclamation();
            this.setVisible(false);
            rec.setVisible(true);
    }//GEN-LAST:event_JreclamationActionPerformed

    private void JstatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JstatistiqueActionPerformed
        Statistique st=new Statistique();
            this.setVisible(false);
            st.setVisible(true);
    }//GEN-LAST:event_JstatistiqueActionPerformed

    private void JclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JclientActionPerformed
        // TODO add your handling code here:
        GereClient gc=new GereClient();
            this.setVisible(false);
            gc.setVisible(true);
    }//GEN-LAST:event_JclientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtRetour;
    private javax.swing.JButton Jclient;
    private javax.swing.JButton Jprest;
    private javax.swing.JButton Jrapport;
    private javax.swing.JButton Jreclamation;
    private javax.swing.JButton Jstatistique;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
