/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.Presentation.Administrateur;

import GoldenCage.dao.PrestataireDAO;
import GoldenCage.entities.Prestataire;
import javax.swing.JOptionPane;

/**
 *
 * @author minoo
 */
public class GererCompte extends javax.swing.JFrame {

    /**
     * Creates new form GererCompte
     */
    public GererCompte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtRetour = new javax.swing.JButton();
        BtModif = new javax.swing.JButton();
        BtSuprim = new javax.swing.JButton();
        BtAjout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new AfficherPrestataire());
        jScrollPane1.setViewportView(jTable1);

        BtRetour.setText("Retour");
        BtRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRetourActionPerformed(evt);
            }
        });

        BtModif.setText("Modifier");
        BtModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtModifActionPerformed(evt);
            }
        });

        BtSuprim.setText("Supprimer");
        BtSuprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSuprimActionPerformed(evt);
            }
        });

        BtAjout.setText("Ajouter");
        BtAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAjoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtRetour)
                        .addGap(127, 127, 127)
                        .addComponent(BtModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(BtSuprim)
                        .addGap(107, 107, 107)
                        .addComponent(BtAjout))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtRetour)
                    .addComponent(BtModif)
                    .addComponent(BtSuprim)
                    .addComponent(BtAjout))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRetourActionPerformed
        // TODO add your handling code here:
        Choix ch=new Choix();
        this.setVisible(false);
        ch.setVisible(true);
    }//GEN-LAST:event_BtRetourActionPerformed

    private void BtAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAjoutActionPerformed
        // TODO add your handling code here:
       AjouterCompte ac=new AjouterCompte();
        this.setVisible(false);
        ac.setVisible(true);
    }//GEN-LAST:event_BtAjoutActionPerformed

    private void BtSuprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSuprimActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
            int id=(int)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            PrestataireDAO prestatairedao=new PrestataireDAO();
            System.out.println(id);
            if(prestatairedao.deletePrestataire(id)==false){
                JOptionPane.showMessageDialog(null,"Un probléme est survenu lors de la suppression");
            }
            else{
                JOptionPane.showMessageDialog(null,"La ligne a été supprimé avec succés");
                jTable1.setModel(new AfficherPrestataire());
            }
            
        }
        else
            JOptionPane.showMessageDialog(null,"Veuillez selectionner une ligne");
    }//GEN-LAST:event_BtSuprimActionPerformed

    private void BtModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtModifActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRow()!=-1){
             Prestataire prest=new Prestataire();
             prest.setIdPrestataire((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
             prest.setAdresse((String)jTable1.getValueAt(jTable1.getSelectedRow(), 4));
             prest.setAdresseMail((String)jTable1.getValueAt(jTable1.getSelectedRow(), 9));
             prest.setFax((int)jTable1.getValueAt(jTable1.getSelectedRow(), 8));
             prest.setGSM((int)jTable1.getValueAt(jTable1.getSelectedRow(), 7));
             prest.setLogin((String)jTable1.getValueAt(jTable1.getSelectedRow(), 2));
             prest.setMotDePasse((String)jTable1.getValueAt(jTable1.getSelectedRow(), 3));
             prest.setNomSociete((String)jTable1.getValueAt(jTable1.getSelectedRow(), 1));
             prest.setPhoto((String)jTable1.getValueAt(jTable1.getSelectedRow(), 11));
             prest.setPresentation((String)jTable1.getValueAt(jTable1.getSelectedRow(), 5));
             prest.setSiteWeb((String)jTable1.getValueAt(jTable1.getSelectedRow(), 10));
             prest.setTel((int)jTable1.getValueAt(jTable1.getSelectedRow(), 6));
             ModifierCompte md=new ModifierCompte(prest);
             this.setVisible(false);
             md.setVisible(true);
         }
         else
            JOptionPane.showMessageDialog(null,"Veuillez selectionner une ligne");
    }//GEN-LAST:event_BtModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererCompte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAjout;
    private javax.swing.JButton BtModif;
    private javax.swing.JButton BtRetour;
    private javax.swing.JButton BtSuprim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
