/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.Presentation.Administrateur;

import GoldenCage.dao.ClientDAO;
import GoldenCage.dao.SendMessage;
import GoldenCage.entities.Client;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author minoo
 */
public class Reclamation extends javax.swing.JFrame {

    /**
     * Creates new form Reclamation
     */
    public Reclamation() {
        initComponents();
        jRadioAccepter.setVisible(false);
        jRadioEnCours.setVisible(false);
        jRadioRefuser.setVisible(false);
        BtEnvoyer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BtRetour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Jsend = new javax.swing.JButton();
        jRadioEnCours = new javax.swing.JRadioButton();
        jRadioRefuser = new javax.swing.JRadioButton();
        jRadioAccepter = new javax.swing.JRadioButton();
        BtEnvoyer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtRetour.setText("Retour");
        BtRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRetourActionPerformed(evt);
            }
        });

        jTable1.setModel(new AfficherReclamation("Date"));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Trier selon:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "Préstaire", "Client" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Jsend.setText("Envoyer Mail");
        Jsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsendActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEnCours);
        jRadioEnCours.setText("En cours de traitement");

        buttonGroup1.add(jRadioRefuser);
        jRadioRefuser.setText("Refuser");

        buttonGroup1.add(jRadioAccepter);
        jRadioAccepter.setText("Accépté");

        BtEnvoyer.setText("Envoyer");
        BtEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEnvoyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BtRetour)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jsend)
                            .addGap(155, 155, 155)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jRadioEnCours)
                        .addGap(94, 94, 94)
                        .addComponent(jRadioRefuser)
                        .addGap(99, 99, 99)
                        .addComponent(jRadioAccepter)
                        .addGap(101, 101, 101)
                        .addComponent(BtEnvoyer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioEnCours)
                    .addComponent(jRadioRefuser)
                    .addComponent(jRadioAccepter)
                    .addComponent(BtEnvoyer))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtRetour)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jsend)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRetourActionPerformed
        // TODO add your handling code here:
        Choix ch=new Choix();
        this.setVisible(false);
        ch.setVisible(true);
    }//GEN-LAST:event_BtRetourActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0){
            jTable1.setModel(new AfficherReclamation("Date"));
        }
        if(jComboBox1.getSelectedIndex()==1){
            jTable1.setModel(new AfficherReclamation("Prestataire"));
        }
        if(jComboBox1.getSelectedIndex()==2){
            jTable1.setModel(new AfficherReclamation("Client"));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsendActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()!=-1){
            jRadioAccepter.setVisible(true);
            jRadioEnCours.setVisible(true);
            jRadioRefuser.setVisible(true);
            BtEnvoyer.setVisible(true);
        }
        else
             JOptionPane.showMessageDialog(null,"Veuillez selectionner une ligne");
        
        
    }//GEN-LAST:event_JsendActionPerformed

    private void BtEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEnvoyerActionPerformed
        // TODO add your handling code here:
       
        String email="";
        if((jRadioAccepter.isSelected()==false)&&(jRadioEnCours.isSelected()==false)&&(jRadioRefuser.isSelected()==false)){
            JOptionPane.showMessageDialog(null,"Veuillez selectionner un choix");
        }
        else 
        {
            if(jRadioAccepter.isSelected()){
                email="Votre reclamation a été accépté";
            }
            else if(jRadioEnCours.isSelected()){
                email="Votre reclamation est en cours de traitement";
            }
            else if(jRadioRefuser.isSelected()){
                   email="Votre reclamation a été refuser";
            }
            String login=(String)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            ClientDAO clientDAO=new ClientDAO();
            Client client=new Client();
            client=clientDAO.getClientFromLogin(login);
            SendMessage sendMessage=new SendMessage();
           if( sendMessage.sendMessage(client.getAdressMail(),"Hello",email)){
               JOptionPane.showMessageDialog(null,"Votre mail a été envoyer");
               jRadioAccepter.setVisible(false);
               jRadioEnCours.setVisible(false);
               jRadioRefuser.setVisible(false);
               BtEnvoyer.setVisible(false);
           }
           else{
               JOptionPane.showMessageDialog(null,"Un probléme a été rencontré");
           }
        }
    }//GEN-LAST:event_BtEnvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reclamation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEnvoyer;
    private javax.swing.JButton BtRetour;
    private javax.swing.JButton Jsend;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioAccepter;
    private javax.swing.JRadioButton jRadioEnCours;
    private javax.swing.JRadioButton jRadioRefuser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
